Repository AY2223S2-CS2113-W15-2/tp, pull requests merged in 2023-04, with the labels that each got.

#154 Add new sequence diagrams for Storage and modify DG
  docs/DeveloperGuide.md
  docs/diagrams/backend/storage/StorageSequenceDiagramRead.puml
  docs/diagrams/backend/storage/StorageSequenceDiagramReset.puml
  docs/diagrams/backend/storage/StorageSequenceDiagramWrite.puml
  docs/static/backend/storage/StorageSequenceDiagramRead.png
  docs/static/backend/storage/StorageSequenceDiagramReset.png
  docs/static/backend/storage/StorageSequenceDiagramWrite.png
Labels: type.Documentation

#204 Modify Backend to treat invalid file as empty
  docs/UserGuide.md
  src/main/java/pocketpal/PocketPal.java
  src/main/java/pocketpal/backend/Backend.java
Labels: type.FunctionalityBug

#156 Fix read file exception
  src/main/java/pocketpal/frontend/commands/AddCommand.java
  src/main/java/pocketpal/frontend/commands/DeleteCommand.java
  src/main/java/pocketpal/frontend/util/CategoryUtil.java
Labels: type.Bug

#211 `Backend`: improve code defensiveness
  src/main/java/pocketpal/backend/constants/MiscellaneousConstants.java
  src/main/java/pocketpal/backend/endpoints/Endpoint.java
  src/main/java/pocketpal/backend/endpoints/EndpointUtil.java
  src/main/java/pocketpal/backend/endpoints/EntriesEndpoint.java
  src/main/java/pocketpal/backend/endpoints/EntryEndpoint.java
  src/main/java/pocketpal/frontend/commands/ViewCommand.java
  src/main/java/pocketpal/frontend/constants/MessageConstants.java
  src/main/java/pocketpal/frontend/exceptions/InvalidEntryIdException.java
  src/main/java/pocketpal/frontend/parser/Parser.java
  src/main/java/pocketpal/frontend/util/StringUtil.java
  src/test/java/pocketpal/backend/endpoints/EndpointUtilTest.java
  src/test/java/pocketpal/backend/endpoints/EntriesEndpointTest.java
  src/test/java/pocketpal/backend/endpoints/EntryEndpointTest.java
  src/test/java/pocketpal/commands/ViewCommandTest.java
  src/test/java/pocketpal/frontend/parser/ParserTest.java
Labels: type.FunctionalityBug

#215 fix: view invalid id
  src/main/java/pocketpal/backend/constants/MiscellaneousConstants.java
  src/main/java/pocketpal/backend/endpoints/EntriesEndpoint.java
  src/main/java/pocketpal/frontend/commands/ViewCommand.java
  src/main/java/pocketpal/frontend/constants/MessageConstants.java
  src/main/java/pocketpal/frontend/parser/Parser.java
  src/test/java/pocketpal/backend/endpoints/EntriesEndpointTest.java
  src/test/java/pocketpal/commands/ViewCommandTest.java
Labels: severity.Medium, type.FunctionalityBug

#155 Fix total expenditure
  src/main/java/pocketpal/data/entrylog/EntryLog.java
  src/main/java/pocketpal/frontend/commands/AddCommand.java
  src/main/java/pocketpal/frontend/ui/UI.java
  src/test/java/pocketpal/commands/ViewCommandTest.java
  src/test/java/pocketpal/data/EntryTestUtil.java
  src/test/java/pocketpal/data/entrylog/EntryLogTest.java
  src/test/java/pocketpal/frontend/ui/UITest.java
Labels: type.Bug

#203 Draft personal PPP
  docs/team/adenteo.md
Labels: type.Documentation

#209 Fix some DG formatting issues
  docs/DeveloperGuide.md
Labels: type.Documentation

#217 Complete refactor of parser class
  src/main/java/pocketpal/backend/endpoints/EntriesEndpoint.java
  src/main/java/pocketpal/data/entrylog/EntryLog.java
  src/main/java/pocketpal/frontend/commands/AddCommand.java
  src/main/java/pocketpal/frontend/commands/EditCommand.java
  src/main/java/pocketpal/frontend/commands/ViewCommand.java
  src/main/java/pocketpal/frontend/constants/MessageConstants.java
  src/main/java/pocketpal/frontend/constants/ParserConstants.java
  src/main/java/pocketpal/frontend/exceptions/UnknownArgumentException.java
  src/main/java/pocketpal/frontend/exceptions/UnknownOptionException.java
  src/main/java/pocketpal/frontend/parser/ParseAddCommand.java
  src/main/java/pocketpal/frontend/parser/ParseByeCommand.java
  src/main/java/pocketpal/frontend/parser/ParseCommand.java
  src/main/java/pocketpal/frontend/parser/ParseDeleteCommand.java
  src/main/java/pocketpal/frontend/parser/ParseEditCommand.java
  src/main/java/pocketpal/frontend/parser/ParseHelpCommand.java
  src/main/java/pocketpal/frontend/parser/ParseViewCommand.java
  src/main/java/pocketpal/frontend/parser/Parser.java
  src/test/java/pocketpal/commands/AddCommandTest.java
  src/test/java/pocketpal/commands/EditCommandTest.java
  src/test/java/pocketpal/commands/ViewCommandTest.java
  src/test/java/pocketpal/data/entrylog/EntryLogTest.java
  src/test/java/pocketpal/frontend/parser/ParserTest.java
Labels: priority.High

#206 Revise user guide to increase clarity
  docs/UserGuide.md
Labels: type.Documentation

#213 Add Introduction in User Guide
  docs/UserGuide.md
Labels: type.Documentation

#218 Add example command usage to help function
  docs/UserGuide.md
  src/main/java/pocketpal/frontend/constants/MessageConstants.java
Labels: type.Documentation

#221 Developer guide revision
  docs/DeveloperGuide.md
  src/main/java/pocketpal/backend/endpoints/EntryEndpoint.java
  src/main/java/pocketpal/frontend/commands/DeleteCommand.java
  src/main/java/pocketpal/frontend/commands/EditCommand.java
  src/main/java/pocketpal/frontend/constants/MessageConstants.java
Labels: type.Documentation

#225 Parser dg revision
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/frontend/parser/ParserClassDiagram.puml
  docs/diagrams/frontend/parser/ParserSequenceDiagram.puml
  docs/static/frontend/parser/ParserClassDiagram.png
  docs/static/frontend/parser/ParserSequenceDiagram.png
  src/main/java/pocketpal/frontend/parser/Parser.java
Labels: type.Documentation

#233 Add link to SimpleDateTime implementation to address issue #194
  docs/UserGuide.md
Labels: type.Documentation

#243 update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/PocketPalSequenceDiagram.puml
  docs/diagrams/backend/BackendMainSequenceDiagram.puml
  docs/diagrams/backend/BackendStartupSequenceDiagram.puml
  docs/diagrams/backend/endpoint/EndpointClassDiagram.puml
  docs/diagrams/backend/endpoint/EntriesEndpointGetSequence.puml
  docs/diagrams/backend/endpoint/EntryEndpointPostSequence.puml
  docs/diagrams/frontend/FrontendSequenceDiagram.puml
  docs/static/PocketPalSequenceDiagram.png
  docs/static/backend/BackendMainSequenceDiagram.png
  docs/static/backend/BackendStartupSequenceDiagram.png
  docs/static/backend/endpoint/EndpointClassDiagram.png
  docs/static/backend/endpoint/EntriesEndpointGetSequence.png
  docs/static/backend/endpoint/EntryEndpointPostSequence.png
  docs/static/frontend/FrontendSequenceDiagram.png
Labels: type.Documentation

#242 Modify VALID_PRICE_REGEX in ParserConstants Class
  src/main/java/pocketpal/frontend/constants/MessageConstants.java
  src/main/java/pocketpal/frontend/constants/ParserConstants.java
  src/test/java/pocketpal/commands/DeleteCommandTest.java
  src/test/java/pocketpal/frontend/parser/ParserTest.java
Labels: priority.Medium, type.FunctionalityBug

#244 Modify checkDateValidity method in ParseCommand Class
  src/main/java/pocketpal/frontend/parser/ParseCommand.java
Labels: type.Bug, severity.Low

#246 Add additional constraints on the prices that users supply
  docs/UserGuide.md
Labels: type.Documentation

#256 Update ViewCommand sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/frontend/commands/ViewCommandOverallSequenceDiagram.puml
  docs/static/frontend/commands/ViewCommandOverallSequenceDiagram.png
Labels: type.Documentation

#255 Add NFR
  docs/DeveloperGuide.md
Labels: type.Documentation

#258 update docs
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/img/codecov_example.png
  docs/team/img/contributions_jinxuan-owyong.png
  docs/team/jinxuan-owyong.md
  src/main/java/pocketpal/backend/endpoints/EntriesEndpoint.java
Labels: type.Documentation
