Repository AY2223S2-CS2113-W15-2/tp, pull requests merged in 2023-03, with the labels that each got.

#29 Add UI
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/constants/MessageConstants.java
  src/main/java/seedu/duke/constants/UIConstants.java
  src/main/java/seedu/duke/ui/UI.java
  text-ui-test/EXPECTED.TXT
Labels: todo

#28 Add Entry and EntryLog
  src/main/java/seedu/duke/constants/EntryConstants.java
  src/main/java/seedu/duke/entrylog/Category.java
  src/main/java/seedu/duke/entrylog/Entry.java
  src/main/java/seedu/duke/entrylog/EntryLog.java
Labels: todo

#44 Unit tests: add ui tests
  src/main/java/seedu/duke/constants/UIConstants.java
  src/main/java/seedu/duke/ui/UI.java
  src/test/java/seedu/duke/ui/UITest.java
Labels: todo

#46 Edit add delete methods, edit entry class
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/main/java/seedu/duke/constants/EntryConstants.java
  src/main/java/seedu/duke/entries/Entry.java
  src/main/java/seedu/duke/entries/Food.java
  src/main/java/seedu/duke/entries/Income.java
  src/main/java/seedu/duke/entries/Other.java
  src/main/java/seedu/duke/exceptions/InvalidCategoryException.java
Labels: todo

#47 Add StorageTest.java and update Storage.java
  .gitignore
  src/main/java/seedu/duke/constants/StorageConstants.java
  src/main/java/seedu/duke/exceptions/InvalidReadFileException.java
  src/main/java/seedu/duke/storage/Database.java
  src/main/java/seedu/duke/storage/Storage.java
  src/main/java/seedu/duke/util/CategoryUtil.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: type.CodeQuality, type.Task

#48 Add junit tests for parser class
  .gitignore
  .vscode/settings.json
  build.gradle
  src/main/java/seedu/duke/constants/MessageConstants.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/parser/ParserTest.java
  text-ui-test/runtest.bat
Labels: type.Task

#57 Edit parser functionality to return Command object
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/constants/MessageConstants.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Task

#56 Add unit tests for Entry and EntryLog
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/main/java/seedu/duke/entries/Entry.java
  src/main/java/seedu/duke/entrylog/EntryLog.java
  src/test/java/seedu/duke/entries/EntryTest.java
  src/test/java/seedu/duke/entrylog/EntryLogTest.java
Labels: type.Task, priority.Medium

#61 Unit tests: Modify to assert errors instead of throwing them
  src/test/java/seedu/duke/parser/ParserTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: type.CodeQuality

#62 Add Junit test for AddCommand and DeleteCommand
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/main/java/seedu/duke/constants/MessageConstants.java
  src/main/java/seedu/duke/exceptions/InvalidEntryIdException.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
  src/test/java/seedu/duke/commands/DeleteCommandTest.java
Labels: type.Task

#64 Update logging
  .gitignore
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/constants/StorageConstants.java
  src/main/java/seedu/duke/entrylog/EntryLog.java
Labels: type.Enhancement

#66 UI class: update methods
  src/main/java/seedu/duke/ui/UI.java
  src/main/java/seedu/duke/util/UIUtil.java
  src/test/java/seedu/duke/ui/UITest.java
Labels: type.Enhancement

#65 Implement-exit-function
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/test/java/seedu/duke/commands/DeleteCommandTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#68 Implement edit function
  src/main/java/seedu/duke/commands/EditCommand.java
  src/main/java/seedu/duke/constants/MessageConstants.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/UI.java
Labels: type.Task, priority.High

#71 Update User Guide
  docs/content/UserGuide.html/start.md
  docs/content/UserGuide.html/summary.md
Labels: type.Documentation

#72 User guide: Features
  docs/content/UserGuide.html/features.md
Labels: type.Documentation, priority.High

#74 Integration: help, bye commands
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/main/java/seedu/duke/constants/MessageConstants.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/UI.java
Labels: priority.High

#77 Fix Storage class unclosed BufferedReader on Exception
  docs/content/DeveloperGuide.html/_index.md
  docs/content/DeveloperGuide.html/design.md
  docs/content/DeveloperGuide.html/nfr.md
  docs/content/DeveloperGuide.html/scope.md
  docs/content/DeveloperGuide.html/stories.md
  docs/content/DeveloperGuide.html/testing.md
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/storage/StorageTest.java
Labels: type.Bug

#87 docs: add backend api
  docs/content/DeveloperGuide.html/_index.md
  docs/content/DeveloperGuide.html/backend/_index.md
  docs/content/DeveloperGuide.html/backend/api/_index.md
  docs/content/DeveloperGuide.html/backend/api/entries.md
  docs/content/DeveloperGuide.html/backend/api/entry.md
Labels: type.Documentation

#92 Implement developer guide for storage
  docs/content/DeveloperGuide.html/_index.md
  docs/content/DeveloperGuide.html/backend/storage.md
Labels: type.Documentation

#93 Update Developer guide manual testing
  META-INF/MANIFEST.MF
  docs/content/DeveloperGuide.html/testing.md
Labels: type.Documentation

#95 Remove redundant print statements
  src/main/java/seedu/pocketpal/frontend/commands/DeleteCommand.java
  src/test/java/seedu/pocketpal/commands/EditCommandTest.java
Labels: type.CodeQuality

#96 Unit tests: add tests for backend
  src/main/java/seedu/pocketpal/backend/endpoints/EntryEndpoint.java
  src/test/java/seedu/pocketpal/backend/BackendTestUtil.java
  src/test/java/seedu/pocketpal/backend/endpoints/EndpointImpl.java
  src/test/java/seedu/pocketpal/backend/endpoints/EndpointTest.java
  src/test/java/seedu/pocketpal/backend/endpoints/EntriesEndpointTest.java
  src/test/java/seedu/pocketpal/backend/endpoints/EntryEndpointTest.java
  src/test/java/seedu/pocketpal/commands/AddCommandTest.java
  src/test/java/seedu/pocketpal/commands/DeleteCommandTest.java
  src/test/java/seedu/pocketpal/commands/EditCommandTest.java
  src/test/java/seedu/pocketpal/data/EntryTestUtil.java
  src/test/java/seedu/pocketpal/data/entrylog/EntryLogTest.java
Labels: type.Task

#97 Update Developer Guide with manual testing and parser implementation
  docs/DeveloperGuide.md
Labels: type.Documentation

#99 Update Parser diagrams image path
  docs/DeveloperGuide.md
Labels: type.Documentation

#101 docs: add diagrams for backend
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/PocketPalArchitecture.drawio
  docs/diagrams/backend/BackendClassDiagram.puml
  docs/diagrams/backend/BackendOverviewClassDiagram.puml
  docs/diagrams/backend/EndpointClassDiagram.puml
  docs/diagrams/communication/SimplifiedHTTPClassDiagram.puml
  docs/diagrams/data/DataStructureClassDiagram.puml
  docs/hugo/About.html/_index.md
  docs/hugo/DeveloperGuide.html/_index.md
  docs/hugo/DeveloperGuide.html/backend/_index.md
  docs/hugo/DeveloperGuide.html/backend/api/_index.md
  docs/hugo/DeveloperGuide.html/backend/api/entries.md
  docs/hugo/DeveloperGuide.html/backend/api/entry.md
  docs/static/PocketPalArchitecture.png
  docs/static/backend/BackendClassDiagram.png
  docs/static/backend/BackendOverviewClassDiagram.png
  docs/static/backend/EndpointClassDiagram.png
  docs/static/communication/SimplifiedHTTPClassDiagram.png
  docs/static/data/DataStructureClassDiagram.png
  src/main/java/seedu/pocketpal/backend/endpoints/EntriesEndpoint.java
  src/main/java/seedu/pocketpal/backend/endpoints/EntryEndpoint.java
  src/main/java/seedu/pocketpal/communication/Request.java
  src/main/java/seedu/pocketpal/data/entry/Entry.java
  src/main/java/seedu/pocketpal/data/entrylog/EntryLog.java
  src/main/java/seedu/pocketpal/data/parsing/EntryLogParser.java
Labels: type.Documentation

#104 Update developer guide with add and delete command
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandActivityDiagram.puml
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/DeleteCommandActivityDiagram.puml
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/static/AddCommandActivityDiagram.png
  docs/static/AddCommandSequenceDiagram.png
  docs/static/DeleteCommandActivityDiagram.png
  docs/static/DeleteCommandSequenceDiagram.png
  src/main/java/seedu/pocketpal/frontend/commands/DeleteCommand.java
Labels: type.Documentation

#109 fix: entry comparison without datetime
  src/main/java/seedu/pocketpal/data/entry/Entry.java
  src/main/java/seedu/pocketpal/data/entrylog/EntryLog.java
  src/test/java/seedu/pocketpal/backend/BackendTestUtil.java
Labels: type.Bug, severity.Low

#111 docs: fix errors in backend diagrams
  docs/diagrams/backend/BackendClassDiagram.puml
  docs/diagrams/backend/BackendOverviewClassDiagram.puml
  docs/diagrams/backend/EndpointClassDiagram.puml
  docs/diagrams/communication/SimplifiedHTTPClassDiagram.puml
  docs/diagrams/data/DataStructureClassDiagram.puml
  docs/static/backend/BackendClassDiagram.png
  docs/static/backend/BackendOverviewClassDiagram.png
  docs/static/backend/EndpointClassDiagram.png
  docs/static/communication/SimplifiedHTTPClassDiagram.png
  docs/static/data/DataStructureClassDiagram.png
Labels: type.Documentation

#113 Add view total expenditure feature
  docs/hugo/v1.0/UserGuide.html/features.md
  src/main/java/seedu/pocketpal/frontend/constants/MessageConstants.java
  src/main/java/seedu/pocketpal/frontend/ui/UI.java
  src/test/java/seedu/pocketpal/frontend/ui/UITest.java
Labels: type.Documentation

#114 Re-organise DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Documentation

#115 Add view by price range function
  src/main/java/seedu/pocketpal/frontend/commands/ViewCommand.java
  src/main/java/seedu/pocketpal/frontend/parser/Parser.java
  src/test/java/seedu/pocketpal/commands/DeleteCommandTest.java
  src/test/java/seedu/pocketpal/commands/ViewCommandTest.java
Labels: type.Enhancement

#116 editCommand diagrams and developer guide
  docs/DeveloperGuide.md
  docs/EditCommandClassDiagram.png
  docs/EditCommandSequenceDiagram.png
  docs/diagrams/EditCommandClassDiagram.puml
  docs/diagrams/EditCommandSequenceDiagram.puml
Labels: type.Documentation, priority.Medium

#118 Modify Storage methods, unit tests, and documentation
  docs/content/DeveloperGuide.html/backend/storage.md
  src/main/java/seedu/pocketpal/backend/Backend.java
  src/main/java/seedu/pocketpal/backend/storage/Storage.java
  src/test/java/seedu/pocketpal/backend/storage/StorageTest.java
Labels: type.Documentation, type.CodeQuality

#119 Fix bug where user can input scientific notation for price
  src/main/java/seedu/pocketpal/frontend/parser/Parser.java
  src/test/java/seedu/pocketpal/frontend/parser/ParserTest.java
Labels: type.Bug

#120 Update documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/AddCommandSequenceDiagramReference.puml
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/diagrams/DeleteCommandSequenceDiagramDeleteResponse.puml
  docs/diagrams/DeleteCommandSequenceDiagramGetResponse.puml
  docs/static/AddCommandSequenceDiagram.png
  docs/static/AddCommandSequenceDiagramReference.png
  docs/static/DeleteCommandSequenceDiagram.png
  docs/static/DeleteCommandSequenceDiagramDeleteResponse.png
  docs/static/DeleteCommandSequenceDiagramGetResponse.png
Labels: type.Documentation

#126 121 bug negative amount accepted when editing an entry
  src/main/java/seedu/pocketpal/frontend/constants/MessageConstants.java
  src/main/java/seedu/pocketpal/frontend/parser/Parser.java
  src/test/java/seedu/pocketpal/frontend/parser/ParserTest.java
Labels: type.Bug, priority.Medium

#128 Filter entry by date
  docs/AboutUs.md
  src/main/java/seedu/pocketpal/backend/endpoints/EntriesEndpoint.java
  src/main/java/seedu/pocketpal/communication/RequestParams.java
  src/main/java/seedu/pocketpal/data/entry/Entry.java
  src/main/java/seedu/pocketpal/data/entrylog/EntryLog.java
  src/main/java/seedu/pocketpal/frontend/commands/ViewCommand.java
  src/main/java/seedu/pocketpal/frontend/constants/MessageConstants.java
  src/main/java/seedu/pocketpal/frontend/exceptions/InvalidDateException.java
  src/main/java/seedu/pocketpal/frontend/exceptions/MissingDateException.java
  src/main/java/seedu/pocketpal/frontend/parser/Parser.java
  src/main/java/seedu/pocketpal/frontend/ui/UI.java
  src/test/java/seedu/pocketpal/commands/EditCommandTest.java
  src/test/java/seedu/pocketpal/commands/ViewCommandTest.java
  src/test/java/seedu/pocketpal/data/entrylog/EntryLogTest.java
  src/test/java/seedu/pocketpal/frontend/parser/ParserTest.java
  src/test/java/seedu/pocketpal/frontend/ui/UITest.java
Labels: type.Enhancement

#145 Parser Class : remove magic numbers
  src/main/java/pocketpal/frontend/constants/EntryConstants.java
  src/main/java/pocketpal/frontend/parser/Parser.java
Labels: type.CodeQuality

#150 Fix formatting of vertical line in UG
  docs/UserGuide.md
Labels: type.Documentation

#151 Fix vertical line formatting error
  docs/UserGuide.md
Labels: type.Documentation
